[package]
name = "processprng"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "lib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 3
codegen-units = 1
lto = "thin"
